apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
  namespace: devops-tools
  labels:
    app: jenkins-server
    app.kubernetes.io/name: jenkins
    app.kubernetes.io/part-of: devops-tools
    app.kubernetes.io/managed-by: kubectl
spec:
  selector:
    app: jenkins-server
  type: NodePort
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 32000
      protocol: TCP
